### ISSUE TITLE
Proposal peer review by Viz Wizards

### ISSUE THREAD

**Issue by tanyageorge** [INFO-526-S24/project-final-VizMasters#1]
The following is the peer review of the project proposal by Viz Wizards. The team members that participated in this review are 

- Nick Ferrante - @n-ferrante
- Jasdeep Singh Jhajj - @Jasdeep-Singh-Jhajj
- Agastya Deshraju - @AgastyaDeshraju
- Gillian McGinnis - @gmcginnis
- Tanya Evita George - @tanyageorge
- Jeremiah Gaiser - @jeremiah-gaiser
- Mrunal Jadhav - @mrunal0699

- Describe the goal of the project.

The goal of the project is to analyze global cancer trends using multiple datasets from One World in Data. They aim to analyze trends in the contribution of cancer to global mortality rates, the age groups that are most affected by cancer, and the type of cancers that are most prevalent in the world.

- Describe the data used or collected.

1. The project will be made using the data sourced from https://ourworldindata.org/cancer curated by Max Roser and Hannah Ritchie.
2. It is a comprehensive and international dataset spanning several years.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

1. A lot of summarization and vizualisation to be done via 'plotly'
2. All questions follow a similar analysis- summarizing their data, organizing it and then visualizing them as interactive plots.
3. The filters that are going to be implemented have been mentioned as well.  

- Is there anything that is unclear from the proposal?

1. The columns that are going to be used for each question have not been mentioned.
2. The particular csv file that will be used to implement a particular question has not been mentioned as there are multiple csv files.
3. Minor formatting in spelling errors within the question section. ('ploty' should be 'plotly')
4. Project description needs to be added at the top.

- Provide constructive feedback on how the team might be able to improve their project.

1. The questions could be extended or phrased in a little more depth.
2. Explanation on how the interactivity of the questions could reach out to the audiences 
3. Question 3 could be extended a bit more as there could be different concentrations of cancers spread in different parts of the world.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

Looking forward to see how interactive they make the project with hovering and adding filters.

- Provide constructive feedback on any issues with file and/or code organization.

1. If head or glimpse was used, all the variables could have be seen and understood better. 
2. Code folding could've been used to hide all the unnecessary wrangle code.
3. The 'Conclusion' and 'Additional Points' have been left empty and it is unclear whether one is supposed to pay attention to it or not.

- (Optional) Any further comments or feedback?

The timeline is really well-organized. Looking forward to seeing your results!

**Comment by MikiKatyal** [comment]
Closing comments for review by Viz Wizards


Unclear section of Review comments

1. The Column set to be used for individual questions will be selected based on the final plot to be used.

2. All the CSV files shown under the Datasets will be used to create more than one plot. The selection of plot to represent the individual data and combination of data will be selected based on the most suitable visualization. The selection of plot will be done based on trial and error method.

3. Spelling correction for 'plotly' is done.

4. Project description is stated under the Project Overview section.




Constructive Feedback for Improvement in project.

1. We have kept the questions simple and inline with the quest about the impact of cancer on mortality.

2. Did not understand the part "interactivity of questions" in the feedback.

3. The reflection of cancer data for different parts of the world will be available as one of the plots in the interactive dashboards. The question 3 is in context of a wider data representation.



Constructive Feedback for issues with file and/or code organization.

1. "head" is already used to show the data and data types in the data structure.

2. Code folding is done for Data wrangling section.

3. Conclusion and Additional Points sections are removed as they were empty.
