### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by navyaa-reddy** [INFO-526-S24/project-final-VizMasters#2]
The following is the peer review of the project proposal by Plot Wizards. The team members that participated in this review are 

- [Sai Navya Reddy Busireddy] - @[navyareddy152]
- [ Nandhini Anne]- @[NandhiniAnne]
- [Anjani Sowmya Bollapragada]- @[asbollapragada]
- [Tejas Bhawari] - @[tezz-us]
- [Srinivasan Poonkundran]- @[kANNISTER]
- [Alexander Berliner] - @[SashaCroatia]
- Mohit Rakesh Taparia- @[mohit-taparia]

- Describe the goal of the project.

The goal of the project is to tap and integrate into extensive datasets related to cancer and find the patterns underlying cancer distribution and its impact on the population.

- Describe the data used or collected.

They collected information on the annual number of deaths caused by cancer, categorized by cancer type and different age groups. They also have the data regarding the share of the population diagnosed with cancer, and its types by age. They also have the number of individuals diagnosed with cancer by age, cancer death rate, and age-standardized-rate index.

- Describe how the research question will be answered, e.g. what approaches/methods will be used.

Question 1 will analyze the percentage contribution of cancer-related deaths by summarizing total deaths from other causes and cancer deaths over the years, visualizing with ggplot2 and plotly. 
Question 2 will compare cancer death rates across age groups, calculating total or average death rates and presenting findings with bar charts. 
Lastly, Question 3 will rank cancer types based on prevalence per 100 people and visualize the top types with a horizontal bar chart.

- Is there anything that is unclear from the proposal?

Everything is clear from the proposal.

- Provide constructive feedback on how the team might be able to improve their project.

The proposal is well-designed and constructive. A clear idea of what the project is about is understood. However, using little complex plots would be creative and interesting.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

We are more interested in understanding what types of cancer are most prevalent across the world and would like to see that highlighted in the presentation.

- Provide constructive feedback on any issues with file and/or code organization.

There are no issues with the file and the code. It is clearly understood. However, the proposal explained the goal and the motivation in the project overview. Also, the repo organization is not mentioned in the proposal.

- (Optional) Any further comments or feedback?
No further comments

**Comment by MikiKatyal** [comment]
Closure Comments

1. Constructive feedback implemented.
