### ISSUE TITLE
Code peer review by Viz Wizards

### ISSUE THREAD

**Issue by tanyageorge** [INFO-526-S24/project-final-VizMasters#4]
The following is the peer review of the project code by [Viz Wizards]. The team members that participated in this review are 

Nick Ferrante - @n-ferrante

Jasdeep Singh Jhajj - @Jasdeep-Singh-Jhajj

Agastya Deshraju - @AgastyaDeshraju

Gillian McGinnis - @gmcginnis

Tanya Evita George - @tanyageorge

Jeremiah Gaiser - @jeremiah-gaiser

Mrunal Jadhav - @mrunal0699

---

#### 1. Purpose of Code
- [X] Clearly defined and understood
- [ ] Ambiguous or unclear

---

#### 2. Code Quality

- [X] Code is clean, readable, and well-organized
- [X] Adequate comments explaining complex or tricky code sections
- [X] Variables, methods, and classes have meaningful names
- [X] Consistent code style (indentation, naming conventions, etc.)

---

#### 3. Documentation

- [X] Code documentation (e.g., comments) is sufficient
- [ ] Readme or other documentation updated if necessary

---

#### 4. Best Practices

- [ ] No hardcoded values; constants used appropriately
- [X] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [ ] Code avoids repetition and promotes reusability

---

#### 5. Additional Comments

- Please provide feedback, areas of improvement, or other observations.

Avoid loading of the same libraries multiple times, rather try to load them commonly in one chunk.
To avoid rendering your gifs each time the site is deployed, you can save them first and then load it.
---

#### 6. Recommendation

- [ ] Approved - ready to be merged
- [X] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

---

**Comment by suryavardhandama** [comment]
Thanks for the feedback
