### ISSUE TITLE
Code peer review

### ISSUE THREAD

**Issue by tezz-us** [INFO-526-S24/project-final-VizMasters#5]
The following is the peer review of the project code by [name of team completing peer review]. The team members that participated in this review are 

Srinivasan Poonkundran- @kANNISTER
Alexander Berliner - @SashaCroatia
Mohit Rakesh Taparia- @mohit-taparia
Sai Navya Reddy Busireddy - @navyareddy152
Nandhini Anne- @NandhiniAnne
Anjani Sowmya Bollapragada- @asbollapragada
Tejas Bhawari - @tezz-us
---

#### 1. Purpose of Code

- [x] Clearly defined and understood
- [x] Ambiguous or unclear

The purpose of the code is somewhat clear and is defined. The code appears to be part of a project related to analyzing cancer data, specifically looking at the number of deaths due to various causes, including cancers, across different countries and years. It also includes functions for data wrangling and plotting to visualize the data.
---

#### 2. Code Quality

- [x] Code is clean, readable, and well-organized
- [ ] Adequate comments explaining complex or tricky code sections
- [x] Variables, methods, and classes have meaningful names
- [x] Consistent code style (indentation, naming conventions, etc.)

The code demonstrates good organization and readability, with room for improvement in adding more comments for clarity, especially within the plotting functions.There is consistency in the use of libraries and functions, contributing to a coherent coding style.
---

#### 3. Documentation

- [x] Code documentation (e.g., comments) is sufficient
- [x] Readme or other documentation updated if necessary

 The code more understandable with the documentation.
---

#### 4. Best Practices

- [ ] No hardcoded values; constants used appropriately
- [x] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [x] Code avoids repetition and promotes reusability

The code generally adheres to good practices in terms of security and privacy
---

#### 5. Additional Comments

- The code shows potential and could be further improved with attention to error handling, documentation and testing.

---

#### 6. Recommendation

- [ ] Approved - ready to be merged
- [x] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

---

**Comment by suryavardhandama** [comment]
Thanks for the feedback
