### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by SashaCroatia** [INFO-526-S24/project-final-VizMasters#6]
The following is the peer review of the Presentation proposal by PlotWizards. The team members that participated in this review are 

Srinivasan Poonkundran- @kANNISTER
Alexander Berliner - @SashaCroatia
Mohit Rakesh Taparia- @mohit-taparia
Sai Navya Reddy Busireddy - @navyareddy152
Nandhini Anne- @NandhiniAnne
Anjani Sowmya Bollapragada- @asbollapragada
Tejas Bhawari - @tezz-us

- Content: Is the research question well designed and is the data being used relevant to the research question?
Yes, the data being used is relevant to the research question. It wasn't clear from the presentation or the slides what their main research questions are as they go straight to showing the results.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Yes they used appropriate visualizations, using time series plots for time series data and bar charts for counting categorical data. They appear to interpret them accurately.
Suggestion: please increase the plot and font size of the plots on the shing app.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
Yes, it appears that there was effort put into the project. However, the project could've been more thought out by having a better organization of the plots on the shiny app as well as a small description stating the purpose of their plots as they don't appear to be answering any project questions.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
The slides are basic but don't commit any blunder in its content or organization. However, like with their shiny app, they have too much text on some slides and the font size is too small.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
Fine overall. They're not reading off a script, but some of them appear to be reading off the slides. Everyone spoke.

**Comment by suryavardhandama** [comment]
Thanks for the feedback.
