### ISSUE TITLE
Presentation peer review by VizWizards

### ISSUE THREAD

**Issue by Jasdeep-Singh-Jhajj** [INFO-526-S24/project-final-VizMasters#7]
The following is the peer review of the Presentation proposal by [Viz Wizards]. The team members that participated in this review are 

Nick Ferrante - @n-ferrante
Jasdeep Singh Jhajj - @Jasdeep-Singh-Jhajj
Agastya Deshraju - @AgastyaDeshraju
Gillian McGinnis - @gmcginnis
Tanya Evita George - @tanyageorge
Jeremiah Gaiser - @jeremiah-gaiser
Mrunal Jadhav - @mrunal0699

- Content: Is the research question well designed and is the data being used relevant to the research question?
Yes the dataset used is relevant enough to their research approach and plots being made. There was no explicit mention of any research question in slides, but they have made their analysis/approach on showcasing population affected by cancer using different plots and shiny app.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
1. Yes, they have made correct use of Horizontal bar plot and Time series plot with annotating the details on each point. Could've used more visually distinct colours as lighter shades looked bit similar.
2. Renaming the snake-cased terms to regular labels could have been better.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
Simple & easy-to-use Shiny was developed to allow for interactivity for all graph types which was good. The font could be bigger for shiny plots.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
1. A couple of the plots did not entirely fit on the screen, it was not easy to see the entire plot along with the legend at all times
2. The slides could benefit from shorter sentences to allow for more time to be spent on the plots themselves.
3. Good conclusion breakdown for visualization interpretations

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
Everyone got equal chance to explain the project well. Although not everyone looked reading off the script, some were reading off the slides.

**Comment by MikiKatyal** [comment]
Thank you for the feedback
